/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.eugen8.jsonapi.simpleapp;

import java.sql.Array;
import java.util.Arrays;

public class App {
   
    public static void main(String[] args) {

    	

    
    }
    
    
    protected static Integer parseAgs(String[] args) {
    	String albumNumberStr = null;
    	Integer albumId = null;
    	
    	return albumId;
    }
}
