/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.eugen8.jsonapi.simpleapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	
	
    @Test 
    public void parseArgsReturnsArgumentId() {
    	
    	Integer albumId = App.parseAgs(new String[] {"42"});
    	
    	assertEquals(Integer.valueOf(42), albumId);
    	
    }
}
